<a href="https://colab.research.google.com/github/JeromeMonte/LACE-58013/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PRELIM EXAM**

Question Number 1

In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print("Multiplication by 1\n", a[0]*b, "\n\n")
print("Multiplication by 2\n", a[1]*b, "\n\n")
print("Multiplication by 3\n", a[2]*b, "\n\n")
print("Multiplication by 4\n", a[3]*b, "\n\n")
print("Multiplication by 5\n", a[4]*b, "\n\n")
print("Multiplication by 6\n", a[5]*b, "\n\n")
print("Multiplication by 7\n", a[6]*b, "\n\n")
print("Multiplication by 8\n", a[7]*b, "\n\n")
print("Multiplication by 9\n", a[8]*b, "\n\n")
print("Multiplication by 10\n", a[9]*b, "\n\n")

Multiplication by 1
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] 


Multiplication by 2
 [[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]] 


Multiplication by 3
 [[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]
 [21]
 [24]
 [27]
 [30]] 


Multiplication by 4
 [[ 4]
 [ 8]
 [12]
 [16]
 [20]
 [24]
 [28]
 [32]
 [36]
 [40]] 


Multiplication by 5
 [[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]
 [50]] 


Multiplication by 6
 [[ 6]
 [12]
 [18]
 [24]
 [30]
 [36]
 [42]
 [48]
 [54]
 [60]] 


Multiplication by 7
 [[ 7]
 [14]
 [21]
 [28]
 [35]
 [42]
 [49]
 [56]
 [63]
 [70]] 


Multiplication by 8
 [[ 8]
 [16]
 [24]
 [32]
 [40]
 [48]
 [56]
 [64]
 [72]
 [80]] 


Multiplication by 9
 [[ 9]
 [18]
 [27]
 [36]
 [45]
 [54]
 [63]
 [72]
 [81]
 [90]] 


Multiplication by 10
 [[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]] 




Question Number 2

In [20]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

a = a*2
b = b*2

print("**All the value of each element are doubled**\n")

print("Multiplication by 1\n", a[0]*b, "\n\n")
print("Multiplication by 2\n", a[1]*b, "\n\n")
print("Multiplication by 3\n", a[2]*b, "\n\n")
print("Multiplication by 4\n", a[3]*b, "\n\n")
print("Multiplication by 5\n", a[4]*b, "\n\n")
print("Multiplication by 6\n", a[5]*b, "\n\n")
print("Multiplication by 7\n", a[6]*b, "\n\n")
print("Multiplication by 8\n", a[7]*b, "\n\n")
print("Multiplication by 9\n", a[8]*b, "\n\n")
print("Multiplication by 10\n", a[9]*b, "\n\n")

**All the value of each element are doubled**

Multiplication by 1
 [[ 4]
 [ 8]
 [12]
 [16]
 [20]
 [24]
 [28]
 [32]
 [36]
 [40]] 


Multiplication by 2
 [[ 8]
 [16]
 [24]
 [32]
 [40]
 [48]
 [56]
 [64]
 [72]
 [80]] 


Multiplication by 3
 [[ 12]
 [ 24]
 [ 36]
 [ 48]
 [ 60]
 [ 72]
 [ 84]
 [ 96]
 [108]
 [120]] 


Multiplication by 4
 [[ 16]
 [ 32]
 [ 48]
 [ 64]
 [ 80]
 [ 96]
 [112]
 [128]
 [144]
 [160]] 


Multiplication by 5
 [[ 20]
 [ 40]
 [ 60]
 [ 80]
 [100]
 [120]
 [140]
 [160]
 [180]
 [200]] 


Multiplication by 6
 [[ 24]
 [ 48]
 [ 72]
 [ 96]
 [120]
 [144]
 [168]
 [192]
 [216]
 [240]] 


Multiplication by 7
 [[ 28]
 [ 56]
 [ 84]
 [112]
 [140]
 [168]
 [196]
 [224]
 [252]
 [280]] 


Multiplication by 8
 [[ 32]
 [ 64]
 [ 96]
 [128]
 [160]
 [192]
 [224]
 [256]
 [288]
 [320]] 


Multiplication by 9
 [[ 36]
 [ 72]
 [108]
 [144]
 [180]
 [216]
 [252]
 [288]
 [324]
 [360]] 


Multiplication by 10
 [[ 40]
 [ 80]
 [120]
 [160]
 [200]
 [240]
 [280]
 [320]
 [360]
 [400]] 




Question Number 3

In [33]:
import numpy as np

print(np.eye(4, 4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question Number 4

In [13]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("The size of the Matrix is: ", len(matrix))
print("The shape and dimension of the Matrix is: ", np.shape(matrix))

The size of the Matrix is:  3
The shape and dimension of the Matrix is:  (3, 4)


Question Number 5

In [38]:
import numpy as np

arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

a = arrayOne+arrayTwo

print("Addition:\n", a, "\n\n")

print("Squared:\n", a*a)

Addition:
 [[20 39 33]
 [25 25 28]] 


Squared:
 [[ 400 1521 1089]
 [ 625  625  784]]
