<a href="https://colab.research.google.com/github/JeromeMonte/LinearAlgebra-58013/blob/main/PythonExercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A. Vector Addition

In [ ]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

A + B + C

array([ 4,  3, -1])

In [ ]:
np.add(A,np.add(B,C))

array([ 4,  3, -1])

In [ ]:
np.sum(B)

2

B. Vector Subtraction

In [ ]:
np.subtract(A,B)

array([-2,  1,  2])

In [ ]:
A-B

array([-2,  1,  2])

C. Vector Multiplication

In [ ]:
np.multiply(A,B)

array([3, 2, 0])

In [ ]:
A * B

array([3, 2, 0])

D. Vector Division

In [ ]:
np.divide(A,B)

array([ 0.33333333,  2.        , -0.        ])

In [ ]:
A / B

array([ 0.33333333,  2.        , -0.        ])

In [ ]:
C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C / D

array([3.9, 1.8, 7.7])

In [ ]:
np.array(A / B, dtype = int)

array([0, 2, 0])