<a href="https://colab.research.google.com/github/JeromeMonte/LinearAlgebra-58013/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MATRIX ALGEBRA**

Associativity Property

In [11]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, 1],
              [3, 1, 2],
              [1, 2, 3]])


LHS = np.dot(np.dot(A, B), C)
RHS = np.dot(A, np.dot(B, C))
AP = np.array_equal(LHS, RHS)

print(LHS,"\n\n",RHS,"\n\n",AP)

[[150  60 132]
 [429 177 384]
 [708 294 636]] 

 [[150  60 132]
 [429 177 384]
 [708 294 636]] 

 True


Distributivity over Addition

In [10]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, 1],
              [3, 1, 2],
              [1, 2, 3]])

LHS = np.dot(A, B + C)
RHS = np.dot(A, B) + np.dot(A, C)
DP = np.array_equal(LHS, RHS)

print(LHS,"\n\n", RHS,"\n\n",DP)

[[ 41  32  32]
 [113  86  86]
 [185 140 140]] 

 [[ 41  32  32]
 [113  86  86]
 [185 140 140]] 

 True


SCALAR

In [12]:
import numpy as np

k = 2

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, 1],
              [3, 1, 2],
              [1, 2, 3]])

LHS = k * np.dot(A, B)
RHS1 = np.dot(k * A, B)
RHS2 = np.dot(A, k * B)
SC = np.array_equal(LHS, RHS1) and np.array_equal(LHS, RHS2)

print(LHS,"\n\n", RHS1,"\n\n", RHS2,"\n\n", SC)

[[ 60  48  36]
 [168 138 108]
 [276 228 180]] 

 [[ 60  48  36]
 [168 138 108]
 [276 228 180]] 

 [[ 60  48  36]
 [168 138 108]
 [276 228 180]] 

 True


Identity Matrix Property

In [14]:
import numpy as np

I = np.identity(3)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, 1],
              [3, 1, 2],
              [1, 2, 3]])

LHS = np.dot(I, A)
RHS = A
IP = np.array_equal(LHS, RHS)

print(LHS,"\n\n", RHS,"\n\n",IP)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 True


Zero Matrix Property

In [15]:
import numpy as np

zero_matrix = np.zeros((3, 3))

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, 1],
              [3, 1, 2],
              [1, 2, 3]])

LHS = np.dot(A, zero_matrix)
RHS = np.dot(zero_matrix, A)
ZP = np.array_equal(LHS, RHS)

print(LHS,"\n\n", RHS,"\n\n",ZP)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

 True


Transpose Property

In [16]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, 1],
              [3, 1, 2],
              [1, 2, 3]])

LHS = np.dot(A, B).T
RHS = np.dot(B.T, A.T)
TP = np.array_equal(LHS, RHS)

print(LHS,"\n\n", RHS,"\n\n",TP)

[[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]] 

 [[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]] 

 True
