<a href="https://colab.research.google.com/github/JeromeMonte/LACE-58013/blob/main/Vector_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


Checking shapes and matrix count

In [1]:
##Checking Shapes
###Shapes tell how many rows and columns are there

import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

balls = len(ball1) + len(ball2)

shape = np.shape(np.array([ball1,ball2]))

print('Ball 1:\n',ball1)
print('\nBall 2:\n',ball2)
print('\nBall Shape\n(Rows, Columns):\n',shape,'\n')
print(np.array([ball1,ball2]))
print('\nThe length of Ball 1 and Ball 2 is',balls)

Ball 1:
 [1 2 3]

Ball 2:
 [ 0  1 -1]

Ball Shape
(Rows, Columns):
 (2, 3) 

[[ 1  2  3]
 [ 0  1 -1]]

The length of Ball 1 and Ball 2 is 6


Operations

In [6]:
##Addition

import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print(A+B)

[ 6 -2]


In [7]:
##Subtraction

import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print(A-B)

[2 8]


In [8]:
##Multiplication

import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print(A*B)

[  8 -15]


In [9]:
##Division

import numpy as np

A = np.array([4,3])
B = np.array([2,-5])

print(A/B)

[ 2.  -0.6]


In [14]:
##Scalar Product

import numpy as np

S = np.array([2])

print(S*A)

[8 6]


In [15]:
##Dot Product

import numpy as np

A = np.array([4,3])
B = np.array([[2],[-5]])

print(np.dot(A,B))

[-7]


In [12]:
##Cross Product

import numpy as np

A = np.array([4,3])
B = np.array([[2],[-5]])

print(A*B)

[[  8   6]
 [-20 -15]]


In [13]:
##Property of Matrix
##Identity Matrix

import numpy as np

c = np.eye(3,3)

print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
##Transpose Matrix

import numpy as np

A = np.array([4,3])
B = np.array([[2],[-5]])

print(np.transpose(B))

[[ 2 -5]]
